# Generated by Django 4.0.3 on 2022-03-19 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='username',
        ),
    ]
