# Generated by Django 4.0.3 on 2022-03-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_student_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='department',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='designation',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
