# Generated by Django 4.0.3 on 2022-04-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0010_alter_emailrecord_semester'),
        ('account', '0006_alter_faculty_department_alter_faculty_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='submitted_feedbacks',
            field=models.ManyToManyField(to='personal.course'),
        ),
    ]
