# Generated by Django 4.0.3 on 2022-04-29 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_student_submitted_feedbacks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='submitted_feedbacks',
        ),
    ]
