# Generated by Django 4.0.3 on 2022-04-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0010_alter_emailrecord_semester'),
        ('account', '0008_remove_student_submitted_feedbacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='submitted_feedbacks',
            field=models.ManyToManyField(to='personal.course'),
        ),
    ]
