# Generated by Django 4.0.3 on 2022-05-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0010_alter_emailrecord_semester'),
        ('account', '0009_student_submitted_feedbacks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='submitted_feedbacks',
            field=models.ManyToManyField(blank=True, to='personal.course'),
        ),
    ]
