# Generated by Django 4.0.3 on 2022-05-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_student_submitted_feedbacks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='anonymous_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
