# Generated by Django 4.0.3 on 2022-05-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedback',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedback',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
