# Generated by Django 4.0.3 on 2022-03-16 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('designation', models.CharField(choices=[('TA', 'Teaching Assistant'), ('Instructor', 'Instructor'), ('Asst Prof', 'Assistant Professor')], max_length=255)),
            ],
        ),
    ]
