# Generated by Django 4.0.3 on 2022-03-16 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_staffrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffrecord',
            name='designation',
            field=models.CharField(choices=[('Teaching Assistant', 'TA'), ('Instructor', 'Instructor'), ('Assistant Professor', 'Asst Prof')], max_length=255),
        ),
    ]
