# Generated by Django 4.0.3 on 2022-03-16 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_alter_staffrecord_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffrecord',
            old_name='email_id',
            new_name='email',
        ),
    ]
