# Generated by Django 4.0.3 on 2022-03-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_rename_email_id_staffrecord_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffrecord',
            name='designation',
            field=models.CharField(choices=[('Teaching Assistant', 'TA'), ('Instructor', 'Instructor'), ('Assistant Professor', 'Asst Prof'), ('Associate Professor', 'Assoc Prof'), ('Professor', 'Prof'), ('Head of Department', 'HOD')], max_length=255),
        ),
    ]
