# Generated by Django 4.0.3 on 2022-03-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0009_emailrecord_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrecord',
            name='semester',
            field=models.CharField(choices=[('One', '1'), ('Two', '2'), ('Three', '3'), ('Four', '4'), ('Five', '5'), ('Six', '6'), ('Seven', '7'), ('Eight', '8')], max_length=50),
        ),
    ]
